spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

loans:
  message: "Welcome to LivemiltonBank loans related QA APIs "
  contactDetails:
    name: "Smitha Ray - QA Lead"
    email: "smitha@livemiltonbank.com"
  onCallSupport:
    - (666) 265-3765
    - (666) 734-8371